name: Maven Build and Publish
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn clean package

    - name: Publish to JFrog Artifactory
      uses: jfrog/setup-jfrog-cli@v1
    
        
    
    - name: Configure Artifactory server
      run: jfrog rt c my-server --url=http://3.111.42.215:8081/artifactory --access-token=$ARTIFACTORY_ACCESS_TOKEN
    - name: Ping Artifactory server
      run: jfrog rt ping
    - name: Upload artifact to Artifactory
      run: jfrog rt u "target/*.jar" my-server/Jfrog-local-repo/
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
